mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: Password1
    driver-class-name: com.mysql.jdbc.Driver